using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class QuizInfoSample : QuizInfo{

	public QuizInfoSample(int quizListSeq){
		gameSeq= 1285;
		quizListSeq= quizListSeq;
		templateQuizSeq= 4206;
		quizResultSeq= 7;
		gameRound= 1;
		inningType= 0;
		quizType= 1203;
		countValue= 30;
		subTitle= "";
		startValue= "0";
		defaultValue= "0";
		maxValue= "10";
		valueInterval= "1";
		multipleYn= 1;
		betShieldYn= 1;
		comboShieldYn= 1;
		stealBaseYn= 0;
		softballYn= 1;
		typeCode= "BB_QZD_FORECAST";
		quizTitle= "다음 타석의 결과를 예측해 보세요.";
		registTime= "20150412154512";
		quizValue= "";
		quizValueExtend= "";
		isFixedPoint= 0;
		isBetPoint= 1;
		isBetPool= 0;
		rewardDividend= "0";
		timeOver= 1;
		closeYN= 0;
		isRefund= 0;
		playerNumber= 31;
		playerName= "이현곤";
		imageName= "baseball_NC_72606.jpg";
		imagePath= "spos/player/baseball/";
		teamSeq= 13;
		teamName= "NC 다이노스";
		teamColor= "#264e96";
		isCancel= 0;
		resultMsg= "";
		order = new List<OrderInfo>();
		OrderInfo orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 1;
		orderInfo.		ratio= "2.9";
		orderInfo.		description= "1루타";
		orderInfo.orderCode = "1B";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 2;
		orderInfo.		ratio= "3.2";
		orderInfo.		description= "2,3루타";
		orderInfo.orderCode = "2B";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 3;
		orderInfo.		ratio= "4";
		orderInfo.		description= "출루";
		orderInfo.orderCode = "BB";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 4;
		orderInfo.		ratio= "3.65";
		orderInfo.		description= "홈런";
		orderInfo.orderCode = "HR";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 5;
		orderInfo.		ratio= "3.16";
		orderInfo.		description= "땅볼";
		orderInfo.orderCode = "GO";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 6;
		orderInfo.		ratio= "3.4";
		orderInfo.		description= "플라이";
		orderInfo.orderCode = "FO";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 7;
		orderInfo.		ratio= "3.32";
		orderInfo.		description= "삼진";
		orderInfo.orderCode = "K";
		order.Add(orderInfo);
		orderInfo = new OrderInfo ();
		orderInfo.		templateQuizSeq= 4206;
		orderInfo.		quizType= 4;
		orderInfo.		orderSeq= 8;
		orderInfo.		ratio= "3.2";
		orderInfo.		description= "병살";
		orderInfo.orderCode = "DP";
		order.Add(orderInfo);

	}
}
